version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/demodb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123  # Güclü bir şifrə istifadə edin!
    networks:
      - spring-network

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123  # Eyni şifrə burada da olmalıdır
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-network
    restart: always

networks:
  spring-network:
    driver: bridge

volumes:
  postgres-data: