# PostgreSQL konfiqurasiyası
listen_addresses = '*'           # Bütün IP ünvanlarında dinləmək

# Təhlükəsizlik parametrləri
password_encryption = scram-sha-256  # Şifrə şifrələmə metodu
ssl = on                             # SSL-i aktiv etmək
ssl_prefer_server_ciphers = on       # Server şifrələmə üstünlüyü

# Performans və resurs parametrləri
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix
max_wal_size = 1GB
min_wal_size = 80MB

# Loq parametrləri
log_timezone = 'UTC'
log_statement = 'none'              # Loq etmə səviyyəsi (none, ddl, mod, all)
log_connections = on                # Qoşulmaları loq et
log_disconnections = on             # Ayrılmaları loq et

# Region və dil parametrləri
datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'
default_text_search_config = 'pg_catalog.english'