spring.application.name=docker-testing

# Daxili ??b?k? qo?ulmas? (Docker Compose il? i?l?m?k üçün)
spring.datasource.url=jdbc:postgresql://postgres:5432/demodb
spring.datasource.username=postgres
spring.datasource.password=güclü_?ifr?_yaz?n
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html